### ISSUE TITLE
Quick question walktrap

### ISSUE THREAD

**Issue by JR-psych** [hfgolino/EGAnet#101]
Hi, 
I have a GGM that i estimated with ggm-modelselect and I would like to use EGAnet to search for clusters in my network.
Is there any chance to import that network?

When i tried using cluster_walktrap in igraph it said:  "Weight vector must be non-negative"
But isnt it the same same algorithm as in your package? Because when I used EGA with my original data it also estimated a network with negative edges and clustering worked.  So I am a bit confused now.

Thank you for your time!

**Comment by AlexChristensen** [comment]
@JR-psych,

At this time, we don't implement the functionality to import networks that are estimated using other methods.

To obtain community detection results from {igraph}, you should use the absolute values of the network. So, something like: `your_communities <- cluster_walktrap(EGAnet::convert2igraph(abs(your_network)))`

When plotting the network, you can use your original network (`your_network`) and the communities identified using the absolute values of the network (`your_communities$wc`).

*Closing comment because issue is outside of {EGAnet}*
