### ISSUE TITLE
bootEGA produces Error in system("wmic OS get FreePhysicalMemory", intern = TRUE) :    'wmic' not found

### ISSUE THREAD

**Issue by avi-kluger** [hfgolino/EGAnet#142]
bootEGA used to run on my computer. After installing 

# devtools::install_github("donaldRwilliams/BGGM")
# devtools::install_github("hfgolino/EGAnet")

it produces 
Error in system("wmic OS get FreePhysicalMemory", intern = TRUE) : 
  'wmic' not found

Any suggestions?

**Comment by AlexChristensen** [comment]
Hi @avi-kluger,

What version of Windows are you using?

**Comment by avi-kluger** [comment]
Hi, here is all the info

***@***.***

**Comment by AlexChristensen** [comment]
In your Windows Command Prompt, can you try:

```

**Comment by AlexChristensen** [comment]
Whoops.. accidentally closed..

In your Windows Command Prompt, can you try:

```
wmic computersystem get totalphysicalmemory 
```

And let me know what you get

**Comment by avi-kluger** [comment]
'wmic' is not recognized as an internal or external command,
operable program or batch file.

**Comment by avi-kluger** [comment]
To clarify, I get `wmic' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by AlexChristensen** [comment]
Hi @avi-kluger,

Thank you for all of the troubleshooting. It appears the Windows setup does not have some of the usual commands that we expect, so I've set up a bypass to avoid this issue and so you can proceed with your analysis.

The check is for the available memory on your computer to ensure you can properly parallelize without crashing R. Without the check, R might crash during parallelization without warning and this check was implemented as a safeguard against R crashing.

In the scheme of things, your analysis is unlikely to be affected but for posterity, if R crashes during parallelization, then it could be because there is not enough memory.

If you download the latest GitHub version, then you should be able to run your analysis:

```
devtools::install_github("hfgolino/EGAnet")
```

**Comment by avi-kluger** [comment]
Hi @AlexChristensen 
After reinstalling, I got in response to
`boot.wmt <- bootEGA(Schema, iter = 500, type = "parametric", seed = 17)`:
Error in memory_available < global_memory_usage * ncores : 
  comparison (<) is possible only for atomic and list types

**Comment by avi-kluger** [comment]
I also rebooted my computer and replicated the above

**Comment by AlexChristensen** [comment]
Looks like I didn't make `available_memory` a function -- it should work now with the latest GitHub version..

**Comment by avi-kluger** [comment]
`devtools::install_github("hfgolino/EGAnet", force = TRUE)` indeed solved the issue. Thank you @AlexChristensen for this help and @AlexChristensen and @hfgolino, for this useful tool. I have been using multidimensional scaling and smallest space analysis for decades to understand data structure in a way not possible with exploratory factor analysis. EGA, with its bootstrapping, gives much improved and sensible interpretations. You can see an example here https://doi.org/10.3389/fpsyg.2022.1010836, and another one I expect to be accepted for publication soon. KUDOS.

**Comment by hfgolino** [comment]
Thanks for your nice words, and for sharing your very interesting work.

Cheers,
Hudson

*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qua., 25 de out. de 2023 às 08:29, Alexander Christensen <
***@***.***> escreveu:
