### ISSUE TITLE
Can you add the itemstability and structural consistency value  for the plot of typical network structure?

### ISSUE THREAD

**Issue by yumu33** [hfgolino/EGAnet#158]
Could you please add an argument in the bootEGA function for displaying the itemstability and structural consistency for typical structure ? the structure now is just a graph of the community. the readability of this plot can be increased by 
 by adding item stability along the nodes and structural consistency within the dimension node (see [egaadhd.pdf](https://github.com/hfgolino/EGAnet/files/15278811/egaadhd.pdf))

**Comment by hfgolino** [comment]
Hi,

thanks for your comment and suggestion.

Unfortunately, we're not going to add that functionality to bootEGA,
because the typical structure is not very informative.

You should use the structure estimated via EGA in your analysis, not the
typical structure.

Best wishes,

Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em sex., 10 de mai. de 2024 às 14:48, yumu33 ***@***.***>
escreveu:
