### ISSUE TITLE
Error in nlminb - NA/NaN Hessian evaluation

### ISSUE THREAD

**Issue by therisingpage** [hfgolino/EGAnet#71]
I'm walking through this tutorial on analyzing Twitter data - [https://uvastatlab.github.io/2019/05/03/an-introduction-to-analyzing-twitter-data-with-r/]. I believe it uses an older version of EGA. 

When I run the EGA function: `ega_tweets <- EGA(tweet_df_cluster, plot.EGA = TRUE, n = NULL)`
I get a list of the variables (ordinal) and an error: `Error in nlminb(start = cache$theta, objective = minObjective, gradient = minGradient,  : NA/NaN Hessian evaluation`

Below is how I installed and ran the package:
```
install_github("hfgolino/EGA", dep = TRUE)
library(EGAnet)
```

This is my first time using R and this package so, I'm unsure if this is an error with how I used the function or if it has been updated?

**Comment by hfgolino** [comment]
Hi, could you, please, explain what tweet_df_cluster is? Is it the raw
(data.frame) data, is it a correlation matrix?

It is very difficult to debug problems without having more information
about your R version, EGAnet version, etc.

Cheers,
Hudson





*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em dom., 12 de jul. de 2020 às 19:32, Lynn Kirabo <notifications@github.com>
escreveu:

**Comment by therisingpage** [comment]
The _tweet_df_cluster_ is a document term matrix converted into a dataframe. 
I'd like to use EGA to create a visualization of word clusters. 

I'm running the following: 
R version -  4.0.2 (2020-06-22)
EGAnet version - 0.9.6
OS - macOS High Sierra
RStudio - 1.3.959

**Comment by hfgolino** [comment]
Great!

Have you removed sparse terms in your DTM? If you have variables with 0
variance, this will be a problem because the correlation matrix won't be
computed. Removing sparse terms in DTM also helps with the subsequent
analysis, since you'll remove hundreds or thousands of variables. The ideal
is to have < 200 words in a DTM for this type of analysis.

Alternatively, you can send me the .RData file with your DTM, and I can see
if I can make it work.

Cheers

*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em seg., 13 de jul. de 2020 às 12:52, Lynn Kirabo <notifications@github.com>
escreveu:

**Comment by therisingpage** [comment]
Ah! Yes. That was the problem. 
There were multiple variables with 0 variance. 
Toggling the threshold in the removeSparseTerms function has resolved the error. 

Thanks a lot!!

**Comment by hfgolino** [comment]
You're very welcome.

If you're analyzing data from Twitter, EGA may not be the best option for
you. Check the dynamic EGA instead (dynEGA). Pre-print here:
https://psyarxiv.com/tfs7c

Cheers

**Comment by therisingpage** [comment]
Thanks for the pointer. I'll check it out.
