### ISSUE TITLE
Item Stability Analysis Error

### ISSUE THREAD

**Issue by rafavsbastos** [hfgolino/EGAnet#77]
To Reproduce:
 � Function error occurred in: homogenize.membership function of itemStability

R and EGAnet versions:
 � R version: 4.0.3
 � EGAnet version: 0.9.9

Operating System:
 � OS: Windows
 � Version: 10 x64 build 19042

**Comment by hfgolino** [comment]
Hi Rafael,

I'm cc'ing Alexander Christensen here, because he is the author of the
itemStability function, and will be better able to debug this error.

Alex, do you mind checking out what's going on with homogenize.membership?

Cheers,

Hudson



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* ***@***.***
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em ter., 13 de abr. de 2021 às 19:22, Rafael Valdece Sousa Bastos <
***@***.***> escreveu:

**Comment by AlexChristensen** [comment]
Hey @rafavsbastos,

Would you mind passing along either the dataset or `bootEGA` output that is causing the issue?

You can send to: alexpaulchristensen@gmail.com

**Comment by AlexChristensen** [comment]
Fixed with latest commit
