### ISSUE TITLE
v. 0.9.9 bug

### ISSUE THREAD

**Issue by Esterng93** [hfgolino/EGAnet#81]
The demo available here [https://cran.r-project.org/web/packages/EGAnet/vignettes/Unique_Variable_Analysis.html](url) gives an error when downloading v. 0.9.9 directly from github through the code below.

devtools::install_github("hfgolino/EGAnet",
                         dependencies = c("Imports", "Suggests"))

The error is in running the UVA function. The error is "subscript out of bounds". The error gets fixed when you delete version 0.9.9 and install 0.9.8. directly from R repository.

**Comment by AlexChristensen** [comment]
Thanks, @Esterng93, for pointing this bug out. The bug was related to a recent update in `UVA` where we've added an automated argument to the algorithm (`auto`), which is now the default.

In the vignette, we've specified `auto = FALSE`, which allows you to continue along with the vignette.

You can re-install the _EGAnet_ package: `devtools::install_github("hfgolino/EGAnet", build_vignettes = TRUE)`

Let us know if this bug persists or another bug arises.

I'm closing this bug for now.
