### ISSUE TITLE
Dimensional Stability issue

### ISSUE THREAD

**Issue by Richmull** [hfgolino/EGAnet#84]
Hi,
I have an issue trying to generate dimensional stability in EGAnet. I'm unsure whether I have made an error in the dimensional stability command but R tells me it's a bug?
I originally used a form of:

sc <- dimStability(boot, orig.wc = ega$wc)

but this seems to have been abbreviated to:

sc <- dimensionStability(bootRSTred)
sc$dimension.stability

Neither seem to work. Can you help please? Thanks in advance.
Rich Mullen
Console output below:

Error in order(names(stability.dimensions)) : argument 1 is not a vector
> sc <- dimensionStability(bootRSTred)

Item Stability Analysis

Organizing data...done

Computing results...Warning in get0(oNam, envir = ns) :
  restarting interrupted promise evaluation
Warning in get0(oNam, envir = ns) : internal error -3 in R_decompress1

An error has occurred in the 'itemStability.plot' function of 'itemStability':

Error in get0(oNam, envir = ns) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ggpubr/R/ggpubr.rdb' is corrupt

Please open a new issue on GitHub (bug report): https://github.com/hfgolino/EGAnet/issues/new/choose

Be sure to provide the following information:

To Reproduce:
 • Function error occurred in: itemStability.plot function of itemStability

R and EGAnet versions:
 • R version: 4.0.2
 • EGAnet version: 0.9.9

Operating System:
 • OS: Darwin
 • Version: 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64
Error in order(names(stability.dimensions)) : argument 1 is not a vector
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by AlexChristensen** [comment]
Hi @Richmull,

It's hard to tell exactly what's happening here. It seems that the error being captured by our error check is:

`Error in get0(oNam, envir = ns) :
lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/ggpubr/R/ggpubr.rdb' is corrupt`

This error is related to the _ggpubr_ package. When it says "corrupt," that usually means something funky occurred since installing the package. Try uninstalling and reinstalling _ggpubr_. Make sure to restart R/RStudio with each uninstall and reinstall.

#### Uninstall
`remove.packages("ggpubr")`

#### Reinstall
`install.packages("ggpubr")`

Then you can try using the `dimensionStability` function again. There might still be another error but it's hard to know for sure.

**Comment by Richmull** [comment]
That did the trick - soved. Thank you Alex

**Comment by AlexChristensen** [comment]
No problem! Cheers
